import React from 'react'
import VerifyEmailForm from "@/shared/components/shared/auth/verify-email-form";

export const metadata = {
  title: 'DTF | Подтверждение почты',
  description: 'Generated by Next.js',
};


const VerifyEmailPage = () => {
  return (
    <div className="flex justify-center items-center min-h-screen w-full">
      <div className="w-[500px] px-10 sm:px-0">
        <VerifyEmailForm />
      </div>

    </div>
  )
}

export default VerifyEmailPage