import React from "react";

export const metadata = {
  title: 'DTF | Вход',
  description: 'Generated by Next.js',
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
    </>
  );
}