import React from 'react'
import ResetPasswordForm
  from "@/shared/components/shared/auth/reset-password-form";

export const metadata = {
  title: 'DTF | Сброс пароля',
  description: 'Generated by Next.js',
};


export default async function ResetPassword() {
  return (
    <div className="flex justify-center items-center min-h-screen w-full">
      <div className="xl:w-1/4 md:w-1/2 w-full px-10 sm:px-0">
        <ResetPasswordForm />
      </div>
    </div>
  );
}